/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import common.Trabajo;
import estructuras.DLLGenerico;
import javax.swing.JOptionPane;

/**
 *
 * @author jra
 */
public class PanelAccionesDLLGenerico extends javax.swing.JPanel {

    public DLLGenerico<Trabajo> lista;
    private PanelTrabajos trabajos;
    private PanelElementos elem;

    /**
     * Creates new form PanelAccionesFIFOGenerico
     */
    public PanelAccionesDLLGenerico() {
        initComponents();
    }

    public PanelAccionesDLLGenerico(PanelTrabajos trabajos, PanelElementos panelElementos) {
        initComponents();
        this.trabajos = trabajos;
        this.elem = panelElementos;
        lista = new DLLGenerico<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarInicio = new javax.swing.JButton();
        btnAgregarFinal = new javax.swing.JButton();
        btnEliminarInicio = new javax.swing.JButton();
        btnEliminarFinal = new javax.swing.JButton();
        btnVerInicio = new javax.swing.JButton();
        btnVerFinal = new javax.swing.JButton();
        btnVerSiguiente = new javax.swing.JButton();
        btnVerAnterior = new javax.swing.JButton();
        btnMostrarOrden = new javax.swing.JButton();
        btnMostrarInverso = new javax.swing.JButton();
        btnMostrarTamano = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(6, 1, 0, 10));

        btnAgregarInicio.setText("Agregar Inicio");
        btnAgregarInicio.addActionListener(this::btnAgregarInicioActionPerformed);
        add(btnAgregarInicio);

        btnAgregarFinal.setText("Agregar Final");
        btnAgregarFinal.addActionListener(this::btnAgregarFinalActionPerformed);
        add(btnAgregarFinal);

        btnEliminarInicio.setText("Quitar Inicio");
        btnEliminarInicio.addActionListener(this::btnEliminarInicioActionPerformed);
        add(btnEliminarInicio);

        btnEliminarFinal.setText("Quitar Final");
        btnEliminarFinal.addActionListener(this::btnEliminarFinalActionPerformed);
        add(btnEliminarFinal);

        btnVerInicio.setText("Mostrar Inicio");
        btnVerInicio.addActionListener(this::btnVerInicioActionPerformed);
        add(btnVerInicio);

        btnVerFinal.setText("Mostrar Final");
        btnVerFinal.addActionListener(this::btnVerFinalActionPerformed);
        add(btnVerFinal);

        btnVerSiguiente.setText("Mostrar Siguiente");
        btnVerSiguiente.addActionListener(this::btnVerSiguienteActionPerformed);
        add(btnVerSiguiente);

        btnVerAnterior.setText("Mostrar Anterior");
        btnVerAnterior.addActionListener(this::btnVerAnteriorActionPerformed);
        add(btnVerAnterior);

        btnMostrarOrden.setText("Mostrar en orden");
        btnMostrarOrden.addActionListener(this::btnMostrarOrdenActionPerformed);
        add(btnMostrarOrden);

        btnMostrarInverso.setText("Mostrar inverso");
        btnMostrarInverso.addActionListener(this::btnMostrarInversoActionPerformed);
        add(btnMostrarInverso);

        btnMostrarTamano.setText("Mostrar tamaño");
        btnMostrarTamano.addActionListener(this::btnMostrarTamanoActionPerformed);
        add(btnMostrarTamano);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        add(btnLimpiar);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarInicioActionPerformed
        if (trabajos.trabajo != null) {
            lista.insertarAlPrincipio(trabajos.trabajo);
            elem.txtElementos.setText(lista.recorrerHaciaAdelante());
            trabajos.trabajo=null;
        } else {
            JOptionPane.showMessageDialog(this, "No hay trabajo registrado");
        }
    }//GEN-LAST:event_btnAgregarInicioActionPerformed

    private void btnEliminarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInicioActionPerformed
        if (lista.estaVacía()) {
            JOptionPane.showMessageDialog(this, "La lista está vacía");
        } else {
            lista.eliminarInicio();
            elem.txtElementos.setText(lista.recorrerHaciaAdelante());
        }
    }//GEN-LAST:event_btnEliminarInicioActionPerformed

    private void btnVerInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerInicioActionPerformed
        if (lista.estaVacía()) {
            JOptionPane.showMessageDialog(this, "La lista está vacía");
        } else {
            JOptionPane.showMessageDialog(this, lista.mostrarPrimero());
        }
    }//GEN-LAST:event_btnVerInicioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        lista.vaciarLista();
        JOptionPane.showMessageDialog(this, "Lista borrada");
        elem.txtElementos.setText("");
        trabajos.trabajo=null;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFinalActionPerformed
        if (trabajos.trabajo != null) {
            lista.insertarAlFinal(trabajos.trabajo);
            elem.txtElementos.setText(lista.recorrerHaciaAdelante());
            trabajos.trabajo=null;
        } else {
            JOptionPane.showMessageDialog(this, "No hay trabajo registrado");
        }
    }//GEN-LAST:event_btnAgregarFinalActionPerformed

    private void btnEliminarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFinalActionPerformed
        if (lista.estaVacía()) {
            JOptionPane.showMessageDialog(this, "La lista está vacía");
        } else {
            lista.eliminarFinal();
            elem.txtElementos.setText(lista.recorrerHaciaAdelante());
        }
    }//GEN-LAST:event_btnEliminarFinalActionPerformed

    private void btnVerFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFinalActionPerformed
        if (lista.estaVacía()) {
            JOptionPane.showMessageDialog(this, "La lista está vacía");
        } else {
            JOptionPane.showMessageDialog(this, lista.nostrarUltimo());
        }
    }//GEN-LAST:event_btnVerFinalActionPerformed

    private void btnVerSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSiguienteActionPerformed
        if(lista.estaVacía()) {
            JOptionPane.showMessageDialog(this, "La lista está vacía");
        } else {
            try {
                JOptionPane.showMessageDialog(this, lista.buscar(trabajos.trabajo).abajo.elem);
            } catch (NullPointerException npe) {
                JOptionPane.showMessageDialog(this, "El trabajo no está en la lista");
            }
        }
    }//GEN-LAST:event_btnVerSiguienteActionPerformed

    private void btnVerAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAnteriorActionPerformed
        if(lista.estaVacía()) {
            JOptionPane.showMessageDialog(this, "La lista está vacía");
        } else {
            try {
                JOptionPane.showMessageDialog(this, lista.buscar(trabajos.trabajo).arriba.elem);
            } catch (NullPointerException npe) {
                JOptionPane.showMessageDialog(this, "El trabajo no está en la lista");
            }

        }
    }//GEN-LAST:event_btnVerAnteriorActionPerformed

    private void btnMostrarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarOrdenActionPerformed
        if (lista.estaVacía()) {
            JOptionPane.showMessageDialog(this, "La lista está vacía");
        } else {
            elem.txtElementos.setText(lista.recorrerHaciaAdelante());
        }
    }//GEN-LAST:event_btnMostrarOrdenActionPerformed

    private void btnMostrarInversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInversoActionPerformed
        if (lista.estaVacía()) {
            JOptionPane.showMessageDialog(this, "La lista está vacía");
        } else {
            elem.txtElementos.setText(lista.recorrerHaciaAtras());
        }
    }//GEN-LAST:event_btnMostrarInversoActionPerformed

    private void btnMostrarTamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTamanoActionPerformed
        if (lista.estaVacía()) {
            JOptionPane.showMessageDialog(this, "La lista está vacía");
        } else {
            JOptionPane.showMessageDialog(this, lista.tamano());
        }
    }//GEN-LAST:event_btnMostrarTamanoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarFinal;
    private javax.swing.JButton btnAgregarInicio;
    private javax.swing.JButton btnEliminarFinal;
    private javax.swing.JButton btnEliminarInicio;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrarInverso;
    private javax.swing.JButton btnMostrarOrden;
    private javax.swing.JButton btnMostrarTamano;
    private javax.swing.JButton btnVerAnterior;
    private javax.swing.JButton btnVerFinal;
    private javax.swing.JButton btnVerInicio;
    private javax.swing.JButton btnVerSiguiente;
    // End of variables declaration//GEN-END:variables
}
