/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import common.Articulo;
import common.Libro;
import common.Revista;
import common.Trabajo;
import javax.swing.JOptionPane;

/**
 *
 * @author jra
 */
public class PanelTrabajos extends javax.swing.JPanel {

    public Trabajo trabajo;

    /**
     * Creates new form PanelElementosTab
     */
    public PanelTrabajos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelElementosTabs = new javax.swing.JTabbedPane();
        panelLibros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBusquedaLibros = new javax.swing.JButton();
        panelArticulos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTituloArt = new javax.swing.JTextField();
        txtAutorArt = new javax.swing.JTextField();
        txtAnioArt = new javax.swing.JTextField();
        btnSaveArt = new javax.swing.JButton();
        btnLimpiarArt = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtRevista = new javax.swing.JTextField();
        btnBusquedaArticulos = new javax.swing.JButton();
        panelRevistas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTituloMag = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        btnSaveMag = new javax.swing.JButton();
        btnLimpiarMag = new javax.swing.JButton();
        txtAutorMag = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtAnioMag = new javax.swing.JTextField();
        btnBusquedaRevista = new javax.swing.JButton();

        panelLibros.setMaximumSize(new java.awt.Dimension(400, 32767));

        jLabel1.setText("Titulo");

        jLabel2.setText("Autor");

        jLabel3.setText("Año publicacion");

        btnSave.setText("Guardar");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnBusquedaLibros.setText("Busqueda");
        btnBusquedaLibros.addActionListener(this::btnBusquedaLibrosActionPerformed);

        javax.swing.GroupLayout panelLibrosLayout = new javax.swing.GroupLayout(panelLibros);
        panelLibros.setLayout(panelLibrosLayout);
        panelLibrosLayout.setHorizontalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibrosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAnio)
                            .addComponent(txtAutor)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLibrosLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnSave)
                        .addGap(29, 29, 29)
                        .addComponent(btnLimpiar)
                        .addGap(30, 30, 30)
                        .addComponent(btnBusquedaLibros)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelLibrosLayout.setVerticalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnLimpiar)
                    .addComponent(btnBusquedaLibros))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        PanelElementosTabs.addTab("Libros", panelLibros);

        jLabel4.setText("Titulo");

        jLabel5.setText("Autor");

        jLabel6.setText("Año publicacion");

        btnSaveArt.setText("Guardar");
        btnSaveArt.addActionListener(this::btnSaveArtActionPerformed);

        btnLimpiarArt.setText("Limpiar");
        btnLimpiarArt.addActionListener(this::btnLimpiarArtActionPerformed);

        jLabel16.setText("Revista: ");

        btnBusquedaArticulos.setText("Busqueda");
        btnBusquedaArticulos.addActionListener(this::btnBusquedaArticulosActionPerformed);

        javax.swing.GroupLayout panelArticulosLayout = new javax.swing.GroupLayout(panelArticulos);
        panelArticulos.setLayout(panelArticulosLayout);
        panelArticulosLayout.setHorizontalGroup(
            panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArticulosLayout.createSequentialGroup()
                .addGroup(panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArticulosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel16)))
                    .addGroup(panelArticulosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnSaveArt)))
                .addGap(28, 28, 28)
                .addGroup(panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArticulosLayout.createSequentialGroup()
                        .addComponent(btnLimpiarArt)
                        .addGap(36, 36, 36)
                        .addComponent(btnBusquedaArticulos))
                    .addGroup(panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtAnioArt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(txtAutorArt)
                        .addComponent(txtTituloArt)
                        .addComponent(txtRevista)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        panelArticulosLayout.setVerticalGroup(
            panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArticulosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTituloArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAutorArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAnioArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveArt)
                    .addComponent(btnLimpiarArt)
                    .addComponent(btnBusquedaArticulos))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        PanelElementosTabs.addTab("Articulos", panelArticulos);

        jLabel7.setText("Titulo");

        jLabel8.setText("Editorial");

        jLabel9.setText("Edición");

        btnSaveMag.setText("Guardar");
        btnSaveMag.addActionListener(this::btnSaveMagActionPerformed);

        btnLimpiarMag.setText("Limpiar");
        btnLimpiarMag.addActionListener(this::btnLimpiarMagActionPerformed);

        jLabel13.setText("Autor:");

        jLabel15.setText("Año publicacion");

        btnBusquedaRevista.setText("Busqueda");
        btnBusquedaRevista.addActionListener(this::btnBusquedaRevistaActionPerformed);

        javax.swing.GroupLayout panelRevistasLayout = new javax.swing.GroupLayout(panelRevistas);
        panelRevistas.setLayout(panelRevistasLayout);
        panelRevistasLayout.setHorizontalGroup(
            panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRevistasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRevistasLayout.createSequentialGroup()
                            .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel13))
                            .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelRevistasLayout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(txtTituloMag, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRevistasLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEdicion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAutorMag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelRevistasLayout.createSequentialGroup()
                        .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSaveMag)
                            .addComponent(jLabel15))
                        .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRevistasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAnioMag))
                            .addGroup(panelRevistasLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnLimpiarMag)
                                .addGap(29, 29, 29)
                                .addComponent(btnBusquedaRevista)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        panelRevistasLayout.setVerticalGroup(
            panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRevistasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTituloMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtAutorMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtAnioMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveMag)
                    .addComponent(btnLimpiarMag)
                    .addComponent(btnBusquedaRevista))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        PanelElementosTabs.addTab("Revistas", panelRevistas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelElementosTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelElementosTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMagActionPerformed
        // TODO add your handling code here:
        guardaTrabajo("revista");
    }//GEN-LAST:event_btnSaveMagActionPerformed

    private void btnLimpiarMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMagActionPerformed
        // TODO add your handling code here:
        limpiaCampos("revista");
    }//GEN-LAST:event_btnLimpiarMagActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiaCampos("libro");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        guardaTrabajo("libro");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBusquedaLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaLibrosActionPerformed
        // TODO add your handling code here:
        busquedaTrabajo("libro");
    }//GEN-LAST:event_btnBusquedaLibrosActionPerformed

    private void btnLimpiarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarArtActionPerformed
        // TODO add your handling code here:
        limpiaCampos("articulo");
    }//GEN-LAST:event_btnLimpiarArtActionPerformed

    private void btnSaveArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveArtActionPerformed
        // TODO add your handling code here:
        guardaTrabajo("articulo");
    }//GEN-LAST:event_btnSaveArtActionPerformed

    private void btnBusquedaArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaArticulosActionPerformed
        // TODO add your handling code here:
        busquedaTrabajo("articulo");
    }//GEN-LAST:event_btnBusquedaArticulosActionPerformed

    private void btnBusquedaRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaRevistaActionPerformed
        // TODO add your handling code here:
        busquedaTrabajo("revista");
    }//GEN-LAST:event_btnBusquedaRevistaActionPerformed

    public void limpiaCampos(String opcion) {
        switch (opcion) {
            case "libro" -> {
                txtTitulo.setText("");
                txtAutor.setText("");
                txtAnio.setText("");
            }
            case "articulo" -> {
                txtTituloArt.setText("");
                txtAutorArt.setText("");
                txtAnioArt.setText("");
                txtRevista.setText("");
            }
            case "revista" -> {
                txtTituloMag.setText("");
                txtAutorMag.setText("");
                txtAnioMag.setText("");
                txtEditorial.setText("");
                txtEdicion.setText("");
            }
        }
    }

    private void guardaTrabajo(String opcion) {
        System.out.println("Elemento a crear: " + opcion);
        if (verificaCampos(opcion)) {
            guardaElemento(opcion);
            limpiaCampos(opcion);
            JOptionPane.showMessageDialog(this, trabajo);
        } else {
            JOptionPane.showMessageDialog(this, "Registro no guardado. Hay campos vacíos");
        }
    }

    private boolean verificaCampos(String tab) {
        return switch (tab) {
            case "libro" ->
                (!txtAutor.getText().isBlank() && !txtTitulo.getText().isBlank() && !txtAnio.getText().isBlank());
            case "articulo" ->
                (!txtTituloArt.getText().isBlank() && !txtAutorArt.getText().isBlank() && !txtAnioArt.getText().isBlank() && !txtRevista.getText().isBlank());
            case "revista" ->
                (!txtTituloMag.getText().isBlank() && !txtAutorMag.getText().isBlank() && !txtAnioMag.getText().isBlank() && !txtEditorial.getText().isBlank() && !txtEdicion.getText().isBlank());
            default ->
                false;
        };
    }

    private void guardaElemento(String tab) {
        System.out.println("Elemento a guardar: " + tab);
        switch (tab) {
            case "libro" ->
                trabajo = new Libro(txtTitulo.getText(), txtAutor.getText(), txtAnio.getText());
            case "articulo" ->
                trabajo = new Articulo(txtTituloArt.getText(), txtAutorArt.getText(), txtAnioArt.getText(), txtRevista.getText());
            case "revista" ->
                trabajo = new Revista(txtTituloMag.getText(), txtEditorial.getText(), txtEdicion.getText(), txtAutorMag.getText(), txtAnioMag.getText());
        }
    }
    
    private void busquedaTrabajo(String tab) {
        System.out.println("Elemento a buscar: " + tab);
        guardaElemento(tab);
        limpiaCampos(tab);
        JOptionPane.showMessageDialog(this, "Elemento almacenado para busqueda:\n "+trabajo);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PanelElementosTabs;
    private javax.swing.JButton btnBusquedaArticulos;
    private javax.swing.JButton btnBusquedaLibros;
    private javax.swing.JButton btnBusquedaRevista;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarArt;
    private javax.swing.JButton btnLimpiarMag;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveArt;
    private javax.swing.JButton btnSaveMag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelArticulos;
    private javax.swing.JPanel panelLibros;
    private javax.swing.JPanel panelRevistas;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAnioArt;
    private javax.swing.JTextField txtAnioMag;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAutorArt;
    private javax.swing.JTextField txtAutorMag;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtRevista;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTituloArt;
    private javax.swing.JTextField txtTituloMag;
    // End of variables declaration//GEN-END:variables
}
