/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import common.Trabajo;
import estructuras.FIFOGenerico;
import javax.swing.JOptionPane;

/**
 *
 * @author jra
 */
public class PanelAccionesFIFOGenerico extends javax.swing.JPanel {

    public FIFOGenerico<Trabajo> cola;
    private PanelTrabajos trabajos;
    private PanelElementos elem;

    /**
     * Creates new form PanelAccionesFIFOGenerico
     */
    public PanelAccionesFIFOGenerico() {
        initComponents();
    }

    public PanelAccionesFIFOGenerico(PanelTrabajos trabajos, PanelElementos panelElementos) {
        initComponents();
        this.trabajos = trabajos;
        this.elem = panelElementos;
        cola = new FIFOGenerico<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(6, 1, 0, 10));

        btnAgregar.setText("ENQUEUE");
        btnAgregar.setActionCommand("ENQUEUE");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        add(btnAgregar);

        btnEliminar.setText("DEQUEUE");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        add(btnEliminar);

        btnVer.setText("PEEK");
        btnVer.addActionListener(this::btnVerActionPerformed);
        add(btnVer);

        btnLimpiar.setText("CLEAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        add(btnLimpiar);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if (trabajos.trabajo != null) {
            cola.enqueue(trabajos.trabajo);
            elem.txtElementos.setText(cola.showQueue());
        } else {
            JOptionPane.showMessageDialog(this, "No hay trabajo registrado");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (cola.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La cola está vacía");
        } else {
            cola.dequeue();
            elem.txtElementos.setText(cola.showQueue());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        if (cola.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La cola está vacía");
        } else {
            JOptionPane.showMessageDialog(this, cola.peek());
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        cola.clear();
        JOptionPane.showMessageDialog(this, "Lista borrada");
        elem.txtElementos.setText(cola.showQueue());
    }//GEN-LAST:event_btnLimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVer;
    // End of variables declaration//GEN-END:variables
}
